### ISSUE TITLE
[SUGGESTION] Add dehydration support

### ISSUE THREAD

**Issue by Sunconure11** [Theoness1/Food-plus#3]
Just what it says on the tin. This can be done via tags

**Comment by Theoness1** [comment]
ok

**Comment by Sunconure11** [comment]
https://github.com/Globox1997/Dehydration/tree/1.18/src/main/resources/data/dehydration/tags/items

**Comment by Theoness1** [comment]
> https://github.com/Globox1997/Dehydration/tree/1.18/src/main/resources/data/dehydration/tags/items

Isn't it working now?

**Comment by Theoness1** [comment]
I have dehydration support

**Comment by Sunconure11** [comment]
Alright, making sure

**Comment by Sunconure11** [comment]
Hm, if I'm interpreting things right, the item use action just has to be for drinking, and that is enough to add support?
